# Generated by Django 4.1.2 on 2022-11-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="posttags",
            old_name="user",
            new_name="author",
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="dashboard.posttags"
            ),
        ),
    ]
