# Generated by Django 4.1.3 on 2022-11-16 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_post_reading_times_post_trending_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="format: required, max-100",
                max_length=100,
                unique=True,
                verbose_name="category name",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="format: required, letters, numbers, underscore, or hyphens",
                max_length=150,
                unique=True,
                verbose_name="The category slug to form URL.",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="meta_title",
            field=models.CharField(
                help_text="The meta title to be used for browser title and SEO.",
                max_length=255,
                unique=True,
                verbose_name="Meta Title",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                help_text="The post slug to form URL.",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name="Post Title"
            ),
        ),
        migrations.AlterField(
            model_name="postmeta",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.post"
            ),
        ),
        migrations.AlterField(
            model_name="posttags",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="format: required, max-50",
                max_length=50,
                unique=True,
                verbose_name="Tag name",
            ),
        ),
        migrations.AlterField(
            model_name="posttags",
            name="slug",
            field=models.SlugField(
                help_text="format: required, letters, numbers, underscore, or hyphens",
                max_length=150,
                unique=True,
                verbose_name="The tag slug to form URL.",
            ),
        ),
    ]
